name = "pontil"
version = "1.0.1"
description = "A Gleam port of GitHub's actions/toolkit"
licences = ["Apache-2.0"]
target = "javascript"
gleam = ">= 1.14.0"

[repository]
type = "github"
user = "halostatue"
repo = "pontil"
path = "pontil"
tag_prefix = "pontil-"

[[documentation.pages]]
title = "Writing a GitHub Action"
path = "writing-a-github-action.html"
source = "guides/writing-a-github-action.md"
[[documentation.pages]]
title = "Differences with @actions/toolkit"
path = "differences-with-toolkit.html"
source = "guides/differences-with-toolkit.md"
[[documentation.pages]]
title = "Changelog"
path = "changelog.html"
source = "CHANGELOG.md"

[[links]]
title = "Licence"
href = "https://github.com/halostatue/pontil/blob/main/LICENCE.md"
[[links]]
title = "Security"
href = "https://github.com/halostatue/pontil/blob/main/SECURITY.md"
[[links]]
title = "Code of Conduct"
href = "https://github.com/halostatue/pontil/blob/main/CODE_OF_CONDUCT.md"
[[links]]
title = "Contributing"
href = "https://github.com/halostatue/pontil/blob/main/CONTRIBUTING.md"
[[links]]
title = "Sponsor"
href = "https://github.com/sponsors/halostatue"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
envoy = ">= 1.1.0 and < 2.0.0"
youid = ">= 1.5.1 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_fetch = ">= 1.4.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
pontil_core = ">= 1.0.0 and < 2.0.0"
pontil_platform = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
glinter = ">= 2.15.0 and < 3.0.0"
choire = ">= 1.0.8 and < 2.0.0"
simplifile = ">= 2.4.0 and < 3.0.0"
take = ">= 1.0.0 and < 2.0.0"
take_promise = ">= 1.0.0 and < 2.0.0"

[tools.glinter]
stats = true

[tools.glinter.rules]
unused_exports = "off"
ffi_usage = "error"
function_complexity = "warning"
module_complexity = "warning"

[tools.glinter.ignore]
"src/pontil/internal/**/*.gleam" = ["label_possible"]

[javascript.deno]
allow_env = true
allow_read = ["gleam.toml", "test"]
allow_write = ["test/_temp"]
