name = "pontil"
version = "0.1.0"
description = "A Gleam port of GitHub's actions/toolkit"
licences = ["Apache-2.0"]
repository = { type = "github", user = "halostatue", repo = "pontil" }

gleam = ">= 1.14.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
envoy = ">= 1.1.0 and < 2.0.0"
simplifile = ">= 2.4.0 and < 3.0.0"
youid = ">= 1.5.1 and < 2.0.0"
shellout = ">= 1.8.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
glinter = ">= 2.11.1 and < 3.0.0"

[tools.glinter]
stats = true

[tools.glinter.rules]
unused_exports = "off"
